import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { davidAdminFavorites } from "@/data/admin-favorites";
import { companies, submissions } from "@/data/market";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outputPath = join(root, "supabase", "seed.sql");

function sql(value: unknown) {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  return `'${String(value).replaceAll("'", "''")}'`;
}

function json(value: unknown) {
  return `${sql(JSON.stringify(value))}::jsonb`;
}

const companyRows = companies
  .map(
    (company) => `(
  ${sql(company.id)},
  ${sql(company.name)},
  ${sql(company.slug)},
  ${sql(company.logo_url)},
  ${sql(company.website_url)},
  ${sql(company.founder_name ?? null)},
  ${sql(company.office_address)},
  ${sql(company.funding_round)},
  ${sql(company.funding_amount)},
  ${sql(company.funding_date)},
  ${sql(company.total_raised)},
  ${sql(company.lead_investor)},
  ${sql(company.funding_note)},
  ${sql(company.category)},
  ${sql(company.stage)},
  ${sql(company.short_description)},
  ${sql(company.one_line_thesis)},
  ${sql(company.why_it_matters)},
  ${sql(company.ai_usage_profile)},
  ${sql(company.openai_fit)},
  ${json(company.founders)},
  ${sql(`{${company.consumption_profile.join(",")}}`)},
  ${sql(company.consumption_intensity)},
  ${sql(company.consumption_note)},
  ${sql(company.recent_activity_text)},
  ${sql(company.recent_activity_date)},
  ${sql(company.is_featured)},
  ${sql(company.is_breakout)},
  ${sql(company.status)},
  ${sql(company.created_at)},
  ${sql(company.updated_at)},
  ${json(company.generated)}
)`,
  )
  .join(",\n");

const submissionRows = submissions
  .map(
    (submission) => `(
  ${sql(submission.company_name)},
  ${sql(submission.website_url)},
  ${sql(submission.founder_name)},
  ${sql(submission.email)},
  ${sql(submission.description)},
  ${sql(submission.status)},
  ${sql(submission.created_at)}
)`,
  )
  .join(",\n");

const favoriteRows = davidAdminFavorites.companyIds
  .map(
    (companyId, index) => `(
  ${sql(davidAdminFavorites.userHandle)},
  ${sql(companyId)},
  ${index + 1}
)`,
  )
  .join(",\n");

const seedSql = `-- Generated by npm run generate:supabase-seed.

insert into public.companies (
  id,
  name,
  slug,
  logo_url,
  website_url,
  founder_name,
  office_address,
  funding_round,
  funding_amount,
  funding_date,
  total_raised,
  lead_investor,
  funding_note,
  category,
  stage,
  short_description,
  one_line_thesis,
  why_it_matters,
  ai_usage_profile,
  openai_fit,
  founders,
  consumption_profile,
  consumption_intensity,
  consumption_note,
  recent_activity_text,
  recent_activity_date,
  is_featured,
  is_breakout,
  status,
  created_at,
  updated_at,
  generated
) values
${companyRows}
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  logo_url = excluded.logo_url,
  website_url = excluded.website_url,
  founder_name = excluded.founder_name,
  office_address = excluded.office_address,
  funding_round = excluded.funding_round,
  funding_amount = excluded.funding_amount,
  funding_date = excluded.funding_date,
  total_raised = excluded.total_raised,
  lead_investor = excluded.lead_investor,
  funding_note = excluded.funding_note,
  category = excluded.category,
  stage = excluded.stage,
  short_description = excluded.short_description,
  one_line_thesis = excluded.one_line_thesis,
  why_it_matters = excluded.why_it_matters,
  ai_usage_profile = excluded.ai_usage_profile,
  openai_fit = excluded.openai_fit,
  founders = excluded.founders,
  consumption_profile = excluded.consumption_profile,
  consumption_intensity = excluded.consumption_intensity,
  consumption_note = excluded.consumption_note,
  recent_activity_text = excluded.recent_activity_text,
  recent_activity_date = excluded.recent_activity_date,
  is_featured = excluded.is_featured,
  is_breakout = excluded.is_breakout,
  status = excluded.status,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  generated = excluded.generated;

insert into public.submissions (
  company_name,
  website_url,
  founder_name,
  email,
  description,
  status,
  created_at
) values
${submissionRows};

insert into public.admin_favorites (
  user_handle,
  company_id,
  rank
) values
${favoriteRows}
on conflict (user_handle, company_id) do update set
  rank = excluded.rank;
`;

writeFileSync(outputPath, seedSql);
console.log(`Wrote ${outputPath}`);
